### ISSUE TITLE
[New Feature] - Please add verbose to Invoke-TwitterRequest

### ISSUE THREAD

**Issue by potatoqualitee** [thedavecarroll/BluebirdPS#103]
It would be helpful to see the method and URL that is being called, 🙇🏼

**Comment by thedavecarroll** [comment]
@potatoqualitee Instead of providing the full web request hashtable, how about something like this?

![image](https://user-images.githubusercontent.com/37391437/184459687-e2f92888-895c-49e1-8d2d-fd3d2e704775.png)

![image](https://user-images.githubusercontent.com/37391437/184459911-9f52e612-fb94-4997-95ab-48f2fa792ad0.png)

![image](https://user-images.githubusercontent.com/37391437/184459729-135d1bc8-7ae3-4897-b16c-ba2566815c0d.png)

Here's how I implemented it:
```powershell
$VerboseProperties = 'Method','Uri','ContentType','OAuthVersion'
if ($RequestParameters.Form) {
    $WebRequestParams.Add('Form',$RequestParameters.Form)
    $VerboseProperties  += 'Form'
} elseif ($RequestParameters.Body) {
    $WebRequestParams.Add('Body',$RequestParameters.Body)
    $VerboseProperties  += 'Body'
}

if ($RequestParameters.InvocationInfo.BoundParameters.ContainsKey('Verbose')) {
    [PSCustomObject]($WebRequestParams + @{ OAuthVersion = $RequestParameters.OAuthVersion }) |
        Select-Object -Property $VerboseProperties | Format-List |
        Out-String | Write-Verbose
}
```

The key is that the `$RequestParameters` has the `InvocationInfo` which will have access to all the top-level bound parameters.

As you can see, the URI isn't going to be pretty. I include all fields for a given object time, and then when the `IncludeExpansions` parameter is used, I include the expansions and all fields for those.

Let me know what you think. (And many apologies on the long turn-around time.)
Thanks!

**Comment by potatoqualitee** [comment]
excellent ⭐ ! tearin it up! 🔥 🚒
