### ISSUE TITLE
Set-TwitterAuthentication:  Essential access

### ISSUE THREAD

**Issue by alagoutte** [thedavecarroll/BluebirdPS#120]
Now, when you add developer account on twitter (https://dev.twitter.com), it is by default Essential Access with only APIv2 support

it is not possible to connect : 

```powershell
Set-TwitterAuthentication: You currently have Essential access which includes access to Twitter API v2 endpoints only. 
If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. 
You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-level
```

After a quick look, there is not account/verify_credentials.json API call with v2...

**Comment by thedavecarroll** [comment]
Looks like there needs to be significant retooling around authentication. Basically, we need to either detect or set the access level, and based on that enable or disable certain functionality. I'll start looking into this over the next week or two.

In order to support the future with OAuth2 and PKCE Flow, we'll need to look into that as well. I found a nodejs example for setting up a command line app to use this. This will be handled in a separate issue.

**Comment by thedavecarroll** [comment]
I believe the intent for the original v1.1 endpoint has been replaced by the [GET /2/users/me](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-me) v2 endpoint. However, the authentication that is supported by this endpoint is only OAuth2 Auth Code Flow with PKCE which the module does not currently support.

**Comment by thedavecarroll** [comment]
No new development will occur for this project.
