### ISSUE TITLE
Use PowerShell Parameter Validation instead of manual parameter validation

### ISSUE THREAD

**Issue by pauby** [thedavecarroll/BluebirdPS#2]
This is more of a discussion point. When going through the code for the `Get-TwitterFollowers` function I noticed this:

```
    if ([string]::IsNullOrWhiteSpace($ScreenName) -and [string]::IsNullOrWhiteSpace($UserId)) {
        'You must supply either a ScreenName or UserId.' | Write-Warning
        return
    } elseif ($ScreenName.Length -gt 0 -and $UserId.Length -gt 0) {
        'You must supply a ScreenName or a UserId, but not both.' | Write-Warning
        return
    }

    if ($PSCmdlet.ParameterSetName -eq 'List') {
        if ($ResultsPerPage -and $ResultsPerPage -notin 1..200) {
            'For a list of follower objects, you can only request up to 200 user objects per page.' | Write-Warning
            return
        } else {
            $ResultsPerPage = 50
        }
    } else {
        if ($ResultsPerPage -and $ResultsPerPage -notin 1..5000) {
            'For list of follower ids, you can only request up to 5000 user is per page.' | Write-Warning
            return
        } else {
            $ResultsPerPage = 5000
        }
    }
```

Was wondering why this isn't being checked in the `param()` block instead of manually? I always tell people to leverage PowerShell's parameter validation rather than writing your own so this stood out to me.

**Comment by thedavecarroll** [comment]
On a few of the functions, I was using the private function `New-ValidationErrorRecord` to generate a _cleaner_ error record when the provided parameters were not valid. I believe this private function was created after `Get-TwitterFollowers`.

Parameter validation is definitely something that needs to be addressed.

Here is where some confusion creeps in:

`Get-TwitterFollowers` connects to the following two endpoint. The maximum and default `ResultsPerPage` for each endpoint is different.
|Endpoint|ResultsPerPage Max|ResultsPerPage Default
|-|-|-|
|followers/list.json|200|50|
|followers/ids.json|5000|5000|

I'll need to see how to implement the two defaults and maximum values within a `ValidateScript`. Since the endpoint is determined by the ParameterSetName, I'm not sure if I can use that in a `ValidateScript`.

I've asked Twitter. Hopefully, someone can provide some insight.

Thanks

**Comment by thedavecarroll** [comment]
Additionally, there are some parameters that can accept an array, but the array cannot exceed a certain count.

During the `ValidateScript`, the count of the array is not available.

Instead of returning with a warning, which is the current behavior, we could simply warn that anything over the maximum count will be truncated. This would need to be handled within the body of the function.

```powershell
Get-TwitterFriendship -ScreenName $Names
WARNING: More than 100 ScreenNames provided. Processing the first 100 only.
```

**Comment by Windos** [comment]
For those array ones, remember that you can include multiple validation options:

```powershell
param (
    [ValidateCount(1,3)] # Needs at least object, but can include up to three
    [ValidateNotNullOrEmpty()]
    [ValidateScript({Test-Item $_})]
    [string[]] $Name
)
```

As a user I'd prefer to be told upfront if I've included an array that's too long, and I should go and fix my code to break it up (as having the cmdlet truncate the array for me could be iffy when I try to figure out "ok... which ones do I need to re do?")

**Comment by thedavecarroll** [comment]
Wowzers! `[ValidateCount()]` satisfies `UserId` and `ScreenName` quite nicely!

So, the question would be: _terminating failure over 100_ OR _warning over 100_?

What do you think @Windos ?

**Comment by Windos** [comment]
Personally, I would vote fail (which validate count will do). That'd give me output saying "hey fool, you can only give me 100 of these" then I know I have to batch them in the code on my end.

**Comment by RobinDadswell** [comment]
I would also vote for fail (by using validate count) as it makes it more clear that something is wrong as opposed to not getting all the data and potentially not seeing the yellow warning
